# Copyright (c) 2017, Intel Corporation
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
# 
#     * Redistributions of source code must retain the above copyright notice,
#       this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in the
#       documentation and/or other materials provided with the distribution.
#     * Neither the name of Intel Corporation nor the names of its contributors
#       may be used to endorse or promote products derived from this software
#       without specific prior written permission.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

FROM continuumio/miniconda3:4.5.4
#MAINTAINER Robert Cohn <Robert.S.Cohn@intel.com>

# This file is automatically generated from tpl.Dockerfile

ENV ACCEPT_INTEL_PYTHON_EULA=yes

RUN conda config --add channels intel\
    && conda install  -y -q intelpython3_full=2019.4 python=3 \
    && conda clean --all \
    && apt-get update -qqq \
    && apt-get install -y -q curl g++ \
    && apt-get autoremove

COPY /conda-configs /conda-configs 
COPY activate-conda.sh activate-conda.sh
RUN ./activate-conda.sh

COPY create-conda-envs.sh create-conda-envs.sh
RUN ./create-conda-envs.sh

# It needs INTEL_SERIAL_NUMBER=XXXX-XXXXXXX
# COPY activate-icc-online.sh activate-icc-online.sh
# RUN ./activate-icc-online.sh

# RUN make nomkl TARGET_ARCH=host
COPY run.sh run.sh
RUN ./run.sh --size 512 --steps 2

# RUN /opt/intel/parallel_studio_xe_2019/uninstall.sh -s